### ISSUE TITLE
failed to connect with nrf52832 developing board on MAC

### ISSUE THREAD

**Issue by Robingwang** [NordicSemiconductor/pc-nrfconnect-programmer#110]
when start Programmer, it indicates below message.
22:23:10.459	Application data folder: /Users/robin/Library/Application Support/nrfconnect/pc-nrfconnect-programmer
22:23:10.646	Error while probing devices: Error occured when get serial numbers. Errorcode: CouldNotOpenDLL (0x7) Lowlevel error: JLINKARM_DLL_NOT_FOUND (ffffff9c)

and after select the developing board, it failed to recognize the board.

22:31:11.892	Unsupported device. The detected device could not be recognized as neither JLink device nor Nordic USB device.

this board is working properly with Programmer on windows platform
![image](https://user-images.githubusercontent.com/46786609/51325437-dceeaa00-1aa7-11e9-9744-1141e6d1bd50.png)

**Comment by bencefr** [comment]
Hi @Robingwang ,
I know at the moment it's not easy to get hold of the related documentation, but as described [here](https://github.com/NordicSemiconductor/pc-nrfconnect-core/#linux-and-macos) on macOS you'll need to install the JLink package separately.

**Comment by Robingwang** [comment]
Thank you for your help. I can work properly now
