### ISSUE TITLE
Requires unreleased nRF Connect ^3.2.0

### ISSUE THREAD

**Issue by chadkennedyonline** [NordicSemiconductor/pc-nrfconnect-programmer#144]
Version 1.2.3 states it requires "nRF Connect ^3.2.0" which is not released.
![Untitled](https://user-images.githubusercontent.com/13368197/64033640-7d16b200-cb12-11e9-80c3-8cc0160f5b76.png)

Of course we can launch anyway, but we get a warning.
![Untitled2](https://user-images.githubusercontent.com/13368197/64033724-b18a6e00-cb12-11e9-9f3e-06c01bf1833f.png)

As far as I can tell, everything is functional.

**Comment by bencefr** [comment]
Terribly sorry about that  be ensured that there's nothing that would break until nRFConnect 3.2 is released which is due very shortly. The bumped requirement only indicates a cosmetic change to the engine.
