### ISSUE TITLE
I can't use nRF Connect for Desktop properly, and the Programmer module in it

### ISSUE THREAD

**Issue by Droid-MAX** [NordicSemiconductor/pc-nrfconnect-programmer#151]
My area has recently increased the network review so that normal development work is difficult. Even using some proxy tools can't solve this problem. Considering that using nrfutil may solve it, but I still can't find a way to download the hex file to nrf52840 dongle directly.

**Comment by Droid-MAX** [comment]
OS Info:
Windows 10 64bit

Software Version:
v3.2.0

Using a series of proxy software such as Shadowsocks/ShadowsocksR/V2Ray failed to solve the problem that the module could not be downloaded normally, and no settings related to the proxy were found in the software.

**Comment by Droid-MAX** [comment]
![image](https://user-images.githubusercontent.com/12762435/65754161-0a194f00-e143-11e9-9dd0-44928fc2586f.png)

Even after manual installation, the Programmer module still cannot be used normally.

**Comment by bencefr** [comment]
Hi @Droid-MAX ,

Sorry for your troubles. We are trying to understand the issue, please clarify for us.
1. Are you using the officially build binaries and app, or did you build core or programmer yourself?
2. When you say "download", do you mean "flash/program/write to device", or do you want to download a hex file from somewhere?
3. When Programmer app doesn't load, please open the dev-console (CTRL+SHIFT+I) and reload the app (CTRL+R). I expect errors will be reported in the console, please share them.

**Comment by Droid-MAX** [comment]
![image](https://user-images.githubusercontent.com/12762435/65764184-9cc3e900-e157-11e9-8a11-c7a0a485fc0d.png)

**Comment by chunfantasy** [comment]
@Droid-MAX , I assume your network blocks the normally usage of the Programmer app. In that case, building programmer from source might be a better solution for you. So could you describe more concrete on your steps how you build and use it?

**Comment by Droid-MAX** [comment]
I just download & install nRF Connect for Desktop, then download the Programmer app source code tarball, extract in node_modules folder, Launch the app. done

**Comment by bencefr** [comment]
@Droid-MAX , the source tarballs on the release page are not supposed to work.
Do you have an issue to install the app by the "INSTALL" button in the launcher window? Is that what you referred to by network restriction and proxy usage?

**Comment by Droid-MAX** [comment]
No, all failure!

**Comment by Droid-MAX** [comment]
If you have a Programmer executable that can be used separately and independently, or if you have a tool that is easier than nrfutil.

**Comment by chunfantasy** [comment]
@Droid-MAX Sorry for seeing your case. As you described above, I am sure there must be a really bad network condition between you and the server where the artifact is hosted since the artifact is only 737Kb as you can see.

This is actually an interesting topic. I would like to find a solution for the use case like yours. Do you mind adding me on Wechat(chunfantasy) so I could help you with a workaround if you wanna solve it at the weekend. Otherwise, we discuss here next week.

**Comment by Droid-MAX** [comment]
The problem still exists.

**Comment by datenreisender** [comment]
After doing what you described above, I am unsure what state your nRF Connect for Desktop is in, so please remove the whole installation of nRF Connect for Desktop again. Especially open the folder `%USERPROFILE%` in your file explorer and remove the folder `.nrfconnect-apps` in it.

There are three options to try now:

## The normal installation

I guess you already tried this, but just to make it clear, this would be the normal way to install the programmer: 
1. Download the nRF Connect for Desktop installer from https://www.nordicsemi.com/Software-and-Tools/Development-Tools/nRF-Connect-for-desktop/Download#infotabs
2. Run the downloaded installer, acknowledge all confirmation dialogs. If an installer for Segger J-Link starts automatically, then also install that.
3. nRF Connect for Desktop automatically started, search for the entry "Programmer" click on the button "Install" next to it. When that button turns to "Open", then click on it and a window like this should appear:

![programmer](https://user-images.githubusercontent.com/260705/65859371-4da0d280-e368-11e9-8689-a92bb7ce4efc.png)

If this does not work, then remove the whole installation again and try the manual installation of the programmer app:

## Manual installation of the programmer app

1. Download the nRF Connect for Desktop installer from https://www.nordicsemi.com/Software-and-Tools/Development-Tools/nRF-Connect-for-desktop/Download#infotabs
2. Run the downloaded installer, acknowledge all confirmation dialogs. If an installer for Segger J-Link starts automatically, then also install that.
3. Close the automatically started nRF Connect for Desktop.
4. Download the file https://developer.nordicsemi.com/.pc-tools/nrfconnect-apps/pc-nrfconnect-programmer-1.2.3.tgz but do not extract it.
5. In your file explorer go to the folder `%USERPROFILE%` again and in it go down to `.nrfconnect-apps` and further into `local`
5. Move the downloaded file pc-nrfconnect-programmer-1.2.3.tgz to that folder `local` without extracting it.
6. Open nRF Connect for Desktop again.
7. The app list should now contain two entries "Programmer": One with the label "local, v1.2.3" below it, with already has a button "Open" beside it. Click on that.

![nRFconnectWithLocalProgrammer](https://user-images.githubusercontent.com/260705/65859390-55607700-e368-11e9-8597-1ac768535d24.png)

## Assistance from you IT department

If neither of these two variants above work, then please seek out help from the people who provided you with your computer. Either your computer installation or your network access is so locked down, that you will be unable to install the nRF Connect for Desktop Programmer app yourself and you need their assistance in installing it.

I will close this issue, as I expect that we cannot help you any further with it.

**Comment by Droid-MAX** [comment]
Can you send me a installer package directly? for Win10 x64 platform.

**Comment by datenreisender** [comment]
How and to where should I send it?

**Comment by Droid-MAX** [comment]
No, even after I uninstalled and reinstalled nRF Connect, it didn’t help. I just tried it.

**Comment by singer-yang** [comment]
I couldnot use nRF connect for desktop as it said "unable to update app list.....". Then I used manual installtion mentioned by datenreisender and succeeded. But my method is a little bit different: I downloaded github zip file and extracted it to "local" path. Now the nRF connnect shows app shortcuts and I can use them.
