### ISSUE TITLE
非常严重的问题

### ISSUE THREAD

**Issue by jinxiangwzh** [NordicSemiconductor/pc-nrfconnect-programmer#242]
Please use the [Nordic DevZone](https://devzone.nordicsemi.com) portal to report bugs, questions or feedback in general. If you would like to suggest code changes, feel free to submit a pull request.
  常常空白界面，无法使用；
重新插拔设备，必须重启软件  不能重新扫描设备

**Comment by datenreisender** [comment]
Please describe issues in English in this project.
