### ISSUE TITLE
Error while probing devices: EnumerateWorker json error

### ISSUE THREAD

**Issue by wind612** [NordicSemiconductor/pc-nrfconnect-programmer#247]
17:18:38.876	Application data folder: C:\Users\xxx\AppData\Roaming\nrfconnect\pc-nrfconnect-ble
17:18:38.917	TypeError: Failed to fetch. Falling back to stored data
17:18:39.391	Error while probing devices: EnumerateWorker json error

**Comment by datenreisender** [comment]
Please update nRF Connect for Desktop to the just released version 3.9. It fixes all `EnumerateWorker` errors known to us. 

If the error still persists, then feel free to reopen this issue and also describe some more details, e.g. which platform you are on and which devices you have connected to you computer.
