### ISSUE TITLE
Whitescreen when launching the app

### ISSUE THREAD

**Issue by itewqq** [NordicSemiconductor/pc-nrfconnect-programmer#414]
![image](https://github.com/NordicSemiconductor/pc-nrfconnect-programmer/assets/30570177/11c984e9-5c99-4e89-a5a0-9a14ebdfa348)

In the console I got:
```
﻿﻿Not allowed to load local resource: file:///C:/Users/hp/.nrfconnect-apps/local/pc-nrfconnect-programmer/dist/index.html?launcherPath=C%3A%5CUsers%5Chp%5CAppData%5CLocal%5CPrograms%5Cnrfconnect%5Cresources%5Capp.asar
```

I've just followed the instructions from https://nordicsemiconductor.github.io/pc-nrfconnect-docs/get_an_existing_app_s_sources

**Comment by itewqq** [comment]
BTW could you please add network proxy support for the nRF Connect Desktop? Sadly github is typically not available in my area.

**Comment by datenreisender** [comment]
> In the console I got:
> 
> ```
> ﻿﻿Not allowed to load local resource: file:///C:/Users/hp/.nrfconnect-apps/local/pc-nrfconnect-programmer/dist/index.html?launcherPath=C%3A%5CUsers%5Chp%5CAppData%5CLocal%5CPrograms%5Cnrfconnect%5Cresources%5Capp.asar
> ```
> 
> I've just followed the instructions from https://nordicsemiconductor.github.io/pc-nrfconnect-docs/get_an_existing_app_s_sources

Did you also compile the app as described on https://nordicsemiconductor.github.io/pc-nrfconnect-docs/app_development? 

(side note: the development documentation is sadly outdated in some regards but this should work)

> BTW could you please add network proxy support for the nRF Connect Desktop? Sadly github is typically not available in my area.

It should be there: https://github.com/NordicSemiconductor/pc-nrfconnect-launcher/blob/main/doc/proxy-settings.md

**Comment by datenreisender** [comment]
I will close this, assuming everything is fine now.
