### ISSUE TITLE
don't support J-Link Lite CortexM

### ISSUE THREAD

**Issue by amigomcu** [NordicSemiconductor/pc-nrfconnect-programmer#59]
hi all,
why to revise nrfconnect-programemer support J-link lite 

https://www.segger.com/products/debug-probes/j-link/models/j-link-lite/j-link-lite-cortex-m/
https://github.com/NordicSemiconductor/pc-nrfconnect-programmer/blob/master/index.jsx

**Comment by chunfantasy** [comment]
Hi @amigomcu ,
Which version of nRF Connect are you using? 2.4.0?
https://www.nordicsemi.com/eng/nordic/Products/nRF-Connect-for-Desktop/nRF-Connect-Windows/56311

**Comment by amigomcu** [comment]
hi chunfantasy,
yes, now i use nRF Connect are you using? 2.4.0 on MacOs.

**Comment by chunfantasy** [comment]
hi @amigomcu ,
Thanks for the info. We do support jlink devices. I am fixing it now.

**Comment by chunfantasy** [comment]
Fixed in master branch.
